local L = LibStub("AceLocale-3.0"):NewLocale("FishingTracker", "ruRU")

if not L then return end
-- Translator ZamestoTV
-- UI Elements
L["FISHING_TRACKER"] = "Fishing Tracker"
L["FISHING_TRACKER_DEBUG_OUTPUT"] = "Отладочный вывод Fishing Tracker"
L["FISHING_TRACKER_GLOBAL_FISH_STATISTICS"] = "Fishing Tracker - Статистика рыбы"
L["TOTAL_CAUGHT"] = "Всего поймано:"
L["FISH_CAUGHT_HERE"] = "Рыбы поймано здесь:"
L["CURRENT_LOCATION_STATS"] = "Статистика текущей локации:"
L["FISH_NAME"] = "Название рыбы"
L["COUNT"] = "Количество"
L["PERCENT"] = "Процент"
L["SESSION"] = "Сессия:"
L["FISH"] = "рыба"
L["FISH_IN"] = "рыбы в"
L["RARE_FISH_CAUGHT_THIS_SESSION"] = "Редкая рыба, пойманная в этой сессии:"
L["FISHING_SESSION_ENDED"] = "Сессия рыбалки завершена:"
L["FISH_PER_HOUR"] = "рыбы/ч"
L["CLOSING_IN"] = "Закрытие через"
L["SECONDS"] = "секунд"
L["UNKNOWN"] = "Неизвестно"
L["UNKNOWN_ZONE"] = "Неизвестная зона"
L["UNKNOWN_SUBZONE"] = "Неизвестная подзона"
L["UNKNOWN_FISHING"] = "Неизвестная рыбалка"
L["MIGRATED_ZONE_DATA"] = "Перенесенные данные зон:"
L["DEBUG_OUTPUT_APPEAR"] = "Отладочный вывод появится здесь, если включен..."
L["ALLIANCE"] = "Альянс"
L["PLAYER IS ALLIANCE"] = "Игрок из Альянса"
L["HORDE"] = "Орда"
L["PLAYER IS HORDE"] = "Игрок из Орды"
L["SKILL"] = "Навык:"
L["NOT_LEARNED_OR"] = "|cFFFF0000Не изучено|r |cFFFFFFFFили|r"
L["NOT_LEARNED"] = "|cFFFF0000Не изучено|r"
L["UNMAPPED"] = "Неизвестно."
L["FISHING_STATISTICS_SUMMARY"] = "Сводка статистики рыбалки:"
L["TOTAL_FISH_CAUGHT"] = "Всего поймано рыбы:"
L["TOTAL_FISH_TYPES"] = "Всего видов рыбы:"
L["TOTAL_ZONES"] = "Всего зон:"
L["LEFT_CLICK"] = "- ЛКМ: Показать/скрыть основное окно"
L["RIGHT_CLICK"] = "- ПКМ: Показать/скрыть глобальную статистику"
L["DRAG_TO_MOVE"] = "- Перетащите для перемещения"
L["MONEY_OR_CURRENCY_DROP"] = "Дроп денег или валюты."
L["NOT_COUNT_IN_DATABASE"] = "Не учтено в базе данных."
L["CHECKED_RAREFISH_SPECIALFISH"] = "отмечено как редкая рыба или особая рыба"
L["BAD_QUALITY"] = "низкое качество"
L["ITEM"] = "Предмет:"
L["SAVED"] = "сохранено."
L["FISHING_IN"] = "Рыбалка в:"
L["YOU_ARE_IN"] = "Вы находитесь в"
L["SKIPPING_LOOT"] = "Пропуск обработки добычи - неверная зона"
L["NO_FISH_CAUGHT_HERE"] = "В этой зоне еще не поймано рыбы."
L["NIL"] = "пусто"
L["IS"] = "является"
L["OR"] = "или"

-- Zone
L["DALARAN"] = "Даларан"
L["DALARAN_(DEADWIND_PASS)"] = "Даларан (Перевал Мертвого Ветра)"
L["DALARAN_(NORTHREND)"] = "Даларан (Нордскол)"
L["DALARAN_(EASTERN_KINGDOMS)"] = "Даларан (Восточные королевства)"
L["DALARAN_(BROKEN_ISLES)"] = "Даларан (Расколотые острова)"
L["SHADOWMOON_VALLEY"] = "Долина Призрачной Луны"
L["SHADOWMOON_VALLEY_(OUTLAND)"] = "Долина Призрачной Луны (Запределье)"
L["SHADOWMOON_VALLEY_(DRAENOR)"] = "Долина Призрачной Луны (Дренор)"
L["NAGRAND"] = "Награнд"
L["NAGRAND_(OUTLAND)"] = "Награнд (Запределье)"
L["NAGRAND_(DRAENOR)"] = "Награнд (Дренор)"

-- Fish Type
L["QUEST"] = "Задание"
L["JUNK"] = "Хлам"
L["ARMOR"] = "Броня"
L["WEAPON"] = "Оружие"
L["TRADESKILL"] = "Профессия"
L["CONSUMABLE"] = "Расходуемое"
L["MISCELLANEOUS"] = "Разное"
L["COOKING"] = "Кулинария"
L["OTHER"] = "Другое"

-- Equipment Enchant Bonus
L["ENCHANTED"] = "Зачаровано:"
L["FISHING_SKILL"] = "Навык рыбалки"
L["FISHING_LURE"] = "Рыболовная приманка"
L["EQUIP"] = "Экипировать:"
L["ON_EQUIP"] = "При экипировке:"
L["DRAGON_ISLES_FISHING_SKILL"] = "Навык рыбалки Драконьих Островов"
L["FISHING"] = "Рыбалка"
L["PERCEPTION"] = "Восприятие"

-- Fishing Skill Name
L["CLASSIC"] = "Классика"
L["OUTLAND"] = "Запределье"
L["NORTHREND"] = "Нордскол"
L["CATACLYSM"] = "Катаклизм"
L["PANDARIA"] = "Пандария"
L["DRAENOR"] = "Дренор"
L["LEGION"] = "Легион"
L["KUL_TIRAN"] = "Кул-Тирас"
L["ZANDALARI"] = "Зандалар"
L["SHADOWLANDS"] = "Темные земли"
L["DRAGON_ISLES"] = "Драконьи острова"
L["KHAZ_ALGAR"] = "Каз Алгар"

-- Slash commands
L["HELP_TITLE"] = "Команды трекера рыбалки %s:"
L["HELP_TOGGLE"] = " - Показать/скрыть окно трекера рыбалки"
L["HELP_STATS"] = " - Показать/скрыть окно глобальной статистики"
L["HELP_LOCK"] = " - Заблокировать/разблокировать рамку"
L["HELP_SOUND"] = " - Звук ВКЛ/ВЫКЛ"
L["HELP_BG"] = " - Показать/скрыть фон или установить прозрачность"
L["HELP_SCALE"] = " - Установить масштаб"
L["HELP_TRANSPARENCY"] = " - Установить прозрачность"
L["HELP_DEBUG"] = " - Вкл/выкл режим отладки (показывает окно отладочного вывода)"
L["HELP_RESETUI"] = " - Сбросить позицию и масштаб окна"
L["HELP_CONVERT"] = " - Конвертировать данные |cFFFFFF00[FishingBuddy]|r в формат |cFFFFFF00[FishingTracker]|r"
L["HELP_HELP"] = " - Показать справочное сообщение"

-- Messages
L["LOADED_MESSAGE"] = "|c7F7F7FFF< %s |cFFFFFFFF%s|r загружен. >|r|cFFFFFFFF -- |r|cFFFFFF00/ft help|r|cFFFFFFFF для справки.|r"
L["FRAME_IS_NOW"] = ": Рамка теперь "
L["LOCKED"] = "заблокирована"
L["UNLOCKED"] = "разблокирована"
L["SOUND"] = ": Звуки "
L["ENABLED"] = "включены"
L["DISABLED"] = "выключены"
L["BACKGROUND"] = ": Фон "
L["DEBUG_MODE"] = ": Режим отладки "
L["SCALE_SET"] = ": Масштаб рамки установлен на "
L["SCALE_MUST"] = ": Масштаб должен быть между 0.5 и 2.0"
L["POSITION_RESET"] = " и позиция сброшена на центр."
L["TRANSPARENCY_SET"] = ": Прозрачность рамки установлена на "
L["BG_TRANSPARENCY_SET"] = ": Прозрачность фона установлена на "
L["BG_TRANSPARENCY_MUST"] = ": Прозрачность фона должна быть между 0.1 и 1"
L["TRANSPARENCY_SET"] = ": Прозрачность рамки установлена на "
L["RESET_UI"] = "Позиция рамки сброшена на значения по умолчанию"
L["SHOWING_FISHING_DATA"] = ": Показ данных рыбалки - Всего:"
L["FRAME_POSITION_RESET"] = ": Позиция рамки сброшена на значения по умолчанию (ЦЕНТР)"

-- Quality names (optional)
L["QUALITY_POOR"] = "Низкое"
L["QUALITY_COMMON"] = "Обычное"
L["QUALITY_UNCOMMON"] = "Необычное"
L["QUALITY_RARE"] = "Редкое"
L["QUALITY_EPIC"] = "Эпическое"
L["QUALITY_LEGENDARY"] = "Легендарное"
L["QUALITY_ARTIFACT"] = "Артефакт"
L["QUALITY_HEIRLOOM"] = "Наследуемое"
